server.port=${PORT:3000}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.mvc.hiddenmethod.filter.enabled=true
app.admin-wallet-address=0xbd166ac8bcd24cdb575440817c995ce113717a21
